-- 코드를 입력하세요
SELECT ICECREAM_INFO.FLAVOR
FROM FIRST_HALF, ICECREAM_INFO
WHERE (TOTAL_ORDER > 3000) AND (INGREDIENT_TYPE = "fruit_based") AND (FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR)
GROUP BY ICECREAM_INFO.FLAVOR
ORDER BY TOTAL_ORDER DESC